export const ROLES = {
  AGENCY_OWNER: "AGENCY_OWNER",
  TEAM_MEMBER: "TEAM_MEMBER",
  SUB_ACCOUNT: "SUB_ACCOUNT",
} as const

export const STAGES = [
  { key: "NEW" as const, name: "New / Open", color: "#94A0B8" },
  { key: "ACCEPTED" as const, name: "Accepted", color: "#5C6BD8" },
  { key: "WORKING" as const, name: "Working", color: "#F59E0B" },
  { key: "PENDING" as const, name: "Pending", color: "#8B5CF6" },
  { key: "REVIEW" as const, name: "Review", color: "#06B6D4" },
  { key: "RESOLVED" as const, name: "Resolved / Closed", color: "#10B981" },
] as const

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  CONNECT: "/connect",
  PORTAL: "/portal",
  ONBOARDING: "/onboarding",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_REQUESTS: "/admin/requests",
  TEAM_DASHBOARD: "/team/dashboard",
  TEAM_BOARD: "/team/board",
  CLIENT_DASHBOARD: "/client/dashboard",
  DASHBOARD: "/dashboard",
  BOARD: "/dashboard/board",
  UNASSIGNED: "/dashboard/unassigned",
  REVIEW: "/dashboard/review",
  TEAM: "/dashboard/team",
  SUB_ACCOUNTS: "/dashboard/sub-accounts",
  REPORTS: "/dashboard/reports",
  MY_PERFORMANCE: "/dashboard/my-performance",
  SETTINGS: "/dashboard/settings",
  AUDIT_LOG: "/dashboard/audit-log",
} as const

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    CONNECT: "/auth/connect",
    REFRESH: "/auth/refresh",
    CHANGE_PASSWORD: "/auth/change-password",
    FIRST_LOGIN_PASSWORD: "/auth/first-login-password",
    MEDIA_STORAGE: "/auth/media-storage",
    IMPERSONATE: "/auth/impersonate",
    ME: "/auth/me",
  },
  PORTAL: {
    ENTER: "/portal/enter",
    ADMIN_ENTER: "/portal/admin-enter",
  },
  SUB_ACCOUNTS: {
    LIST: "/sub-accounts",
    REQUESTS: "/sub-accounts/requests",
    OVERVIEW: "/sub-accounts/overview",
    CONNECT: "/sub-accounts/connect",
    APPROVE: (id: string) => `/sub-accounts/${id}/approve`,
    REJECT: (id: string) => `/sub-accounts/${id}/reject`,
    STATUS: (id: string) => `/sub-accounts/${id}/status`,
    BULK_APPROVE: "/sub-accounts/bulk-approve",
  },
  USERS: {
    TEAM: "/users/team",
    TEAM_SYNC_GHL: "/users/team/sync-ghl",
    TEAM_BY_ID: (id: string) => `/users/team/${id}`,
    AVAILABILITY: "/users/availability",
    STATS_ME: "/users/stats/me",
    STATS_ALL: "/users/stats/all",
    SUB_ACCOUNTS: "/users/sub-accounts",
  },
  TICKETS: {
    LIST: "/tickets",
    MINE: "/tickets/mine",
    MY: "/tickets/my",
    UNASSIGNED: "/tickets/unassigned",
    REVIEW: "/tickets/review",
    BY_ID: (id: string) => `/tickets/${id}`,
    MOVE_STAGE: (id: string) => `/tickets/${id}/stage`,
    ASSIGN: (id: string) => `/tickets/${id}/assign`,
    COMMENT: (id: string) => `/tickets/${id}/comment`,
    ATTACHMENTS: (id: string) => `/tickets/${id}/attachments`,
    HISTORY: (id: string) => `/tickets/${id}/history`,
    APPROVE: (id: string) => `/tickets/${id}/approve`,
    REJECT: (id: string) => `/tickets/${id}/reject`,
  },
  SOCIAL: {
    ORDERS: "/social/orders",
    ORDER_BY_ID: (id: string) => `/social/orders/${id}`,
    ACCEPT: (id: string) => `/social/orders/${id}/accept`,
    RESPOND: (id: string) => `/social/orders/${id}/respond`,
    ASSIGN: (id: string) => `/social/orders/${id}/assign`,
    STATUS: (id: string) => `/social/orders/${id}/status`,
    PROGRESS: (id: string) => `/social/orders/${id}/progress`,
    CONFIRM: (id: string) => `/social/orders/${id}/confirm`,
    REQUEST_CHANGES: (id: string) => `/social/orders/${id}/request-changes`,
    CANCEL: (id: string) => `/social/orders/${id}/cancel`,
    FILES: (id: string) => `/social/orders/${id}/files`,
    SUB_ACCOUNT_PROFILE: (id: string) => `/social/sub-accounts/${id}/profile`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  ANALYTICS: {
    DASHBOARD: "/analytics/dashboard",
  },
  AUDIT_LOGS: "/audit-logs",
} as const

export const QUERY_KEYS = {
  AUTH: {
    ME: ["auth", "me"] as const,
  },
  SUB_ACCOUNT_REQUESTS: ["sub-accounts", "requests"] as const,
  SUB_ACCOUNTS_ALL: ["sub-accounts", "all"] as const,
  SUB_ACCOUNTS_OVERVIEW: ["sub-accounts", "overview"] as const,
  TICKETS: ["tickets"] as const,
  TICKET: (id: string) => ["ticket", id] as const,
  MY_TICKETS: ["tickets", "mine"] as const,
  UNASSIGNED: ["tickets", "unassigned"] as const,
  REVIEW: ["tickets", "review"] as const,
  TEAM_MEMBERS: ["users", "team"] as const,
  SUB_ACCOUNTS: ["users", "sub-accounts"] as const,
  SOCIAL_ORDERS: ["social", "orders"] as const,
  SOCIAL_ORDER: (id: string) => ["social", "order", id] as const,
  SUB_ACCOUNT_PROFILE: (id: string) => ["social", "profile", id] as const,
  NOTIFICATIONS: ["notifications"] as const,
  UNREAD_COUNT: ["notifications", "unread-count"] as const,
  ANALYTICS: ["analytics"] as const,
  AUDIT_LOGS: ["audit-logs"] as const,
} as const
